# Generated by Django 3.2.6 on 2021-09-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128)),
                ('time', models.DateTimeField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
